const data = {
  productsItems: [
    {
      id: 1,
      img: " https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0aSg3g6sWwu2LaFsRdOuGkECfe_abm8uWPg&usqp=CAU",
      name: "Beginner Full Stack Web Development",
      instru: "james john",
      views: "1320",
      text: "Learn web development with HTML, CSS, Bootstrap 4, ES6 React and Node",
      price: "90",
      time: "12h",
      type: "fullstack",
    },
    {
      id: 2,
      img: " https://www.hostinger.com/tutorials/wp-content/uploads/sites/2/2021/08/bootstrap-2.png",
      name: "bootstrap 4,5 ",
      instru: "james zaki",
      views: "3100",
      text: "Learn html5 and css3 with prof instructor and find your job with us",
      price: "40",
      time: "12h",
      type: "frontend",
    },
    {
      id: 3,
      img: "https://www.arageek.com/wp-content/uploads/html5-intro.jpg",
      name: "Basic HTML5 CSS3",
      instru: "osama elzero",
      views: "2000",
      text: "Learn html5 and css3 with prof instructor and find your job with us",
      price: "80",
      time: "12h",
      type: "frontend",
    },
    {
      id: 4,
      img: "https://e3arabi.com/wp-content/uploads/2020/12/Front-End-Development-Bundle.jpg",
      name: "frontend web development",
      instru: "abdulrahman alaa",
      views: "1200",
      text: "Learn html5 and css3 with prof instructor and find your job with us",
      price: "100",
      time: "12h",
      type: "frontend",
    },
    {
      id: 5,
      img: "https://www.temok.com/blog/wp-content/uploads/2020/04/backend2.jpg",
      name: "backend web development",
      instru: "mohamed ali",
      views: "1200",
      text: "Learn html5 and css3 with prof instructor and find your job with us",
      price: "90",
      time: "12h",
      type: "backend",
    },
    {
      id: 6,
      img: "https://ms314006.github.io/static/b7a8f321b0bbc07ca9b9d22a7a505ed5/97b31/React.jpg",
      name: "react",
      instru: "sami ali",
      views: "1200",
      text: "Learn trml5 and css3 with prof instructor and finfd ypur job with us",
      price: "130",
      time: "12h",
      type: "frontend",
    },
    {
      id: 7,
      img: "https://3cthinkers.com/en/wp-content/uploads/2017/03/dynamicpages.jpeg",
      name: "php",
      instru: "Mustafa barzan",
      views: "1200",
      text: "Learn html5 and css3 with prof instructor and find your job with us",
      price: "50",
      time: "12h",
      type: "backend",
    },
    {
      id: 8,
      img: "https://img.youtube.com/vi/CQYoKFm6w3w/hqdefault.jpg",
      name: "java script , mysQl",
      // instru: "kid jml",
      views: "1200",
      text: "Learn html5 and css3 with prof instructor and find your job with us",
      price: "40",
      time: "12h",
      type: "backend",
    },
    {
      id: 9,
      img: "https://miro.medium.com/max/1200/1*MCiNLBzUI-LWK_PhVwq0xA.png",
      name: " Sass,CSS3",
      instru: "Mustafa barzan",
      views: "1200",
      text: "Learn html5 and css3 with prof instructor and find your job with us",
      price: "50",
      time: "12h",
      type: "fullstack",
    },
  ],
};

export default data;
