const data = {
  dataScience: [
    {
      id: 10,
      img: "https://www.aacp.org/sites/default/files/2020-06/apn-20issue3-hero-02.png",
      name: " Machine learning from A_Z ",
      instru: "james john",
      views: "1320",
      text: "Learn data science with from zero to hero and change the future",
      price: "130",
      priceValue: "130-240",
    },
    {
      id: 2,
      img: "https://bigdataanalyticsnews.com/wp-content/uploads/2021/04/Feature-Engineering.png",
      name: "Python for data science and machine learning bootcamp ",
      instru: "james zaki",
      views: "3100",
      text: "Learn data science with from zero to hero and change the future",
      price: "90",
      priceValue: "40-120",
    },
    {
      id: 3,
      img: "https://miro.medium.com/max/1200/1*K6ctE0RZme0cqMtknrxq8A.png",
      name: " AI artificial intellegence",
      instru: "ahmed shokair",
      views: "2000",
      text: "Learn data science with from zero to hero and change the future",
      price: "400",
      priceValue: "250-500",
    },
    {
      id: 4,
      img: "https://miro.medium.com/max/1000/1*omNpCR7NFy2D6uq6XI9ayA.jpeg",
      name: " real life data science exercises  ",
      instru: "mohammed nadir",
      views: "1200",
      text: "Learn data science with from zero to hero and change the future",
      price: "90",
      priceValue: "40-120",
    },
    {
      id: 5,
      img: "https://miro.medium.com/max/2000/1*g8YLVZSWME7gM6RoMKQgxw.jpeg",
      name: " satisticis for data science  ",
      instru: "mohamed ali",
      views: "1200",
      text: "Learn data science with from zero to hero and change the future",
      price: "40",
      priceValue: "40-120",
    },
    {
      id: 6,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQu_zCunOZkzUz7RS7o0aQLavhUYV66r851NmtBIZ1JIOvbdWJ9fPXpvwHJZx08tBHlYpw&usqp=CAU",
      name: " machine learning basics",
      instru: "khalid jamal",
      views: "1200",
      text: "Learn data science with from zero to hero and change the future",
      price: "280",
      priceValue: "250-500",
    },
    {
      id: 7,
      img: "https://miro.medium.com/max/748/1*oT_LIBILeSEWEF3UPV7rLg.png",
      name: "nodejs and vuejs",
      instru: "Mustafa barzan",
      views: "1200",
      text: "Learn data science with from zero to hero and change the future",
      price: "130",
      priceValue: "130-240",
    },
    {
      id: 8,
      img: "https://one-educationgroup.com/wp-content/uploads/2021/07/Data-Science-TH-1.jpg",
      name: " complete data science ...",
      instru: "khalid jamal",
      views: "1200",
      text: "Learn data science with from zero to hero and change the future",
      price: "300",
      priceValue: "250-500",
    },
    {
      id: 9,
      img: "https://www.northeastern.edu/graduate/blog/wp-content/uploads/2020/06/iStock-1221293664-1.jpg",
      name: " design machines with new technical",
      instru: "Mustafa barzan",
      views: "1200",
      text: "Learn data science with from zero to hero and change the future",
      price: "210",
      priceValue: "130-240",
    },
  ],
};

export default data;
