const data = {
  MobileData: [
    {
      id: 1,
      img: "https://buildfire.com/wp-content/uploads/2018/03/17-top-mobile-development-practices.jpg",
      name: "beginner flutter course  ",
      instru: "james john",
      views: "1320",
      text: "  Learn mobile development with professional teachers",
      price: "130",
      priceValue: "91-150",
    },
    {
      id: 2,
      img: "https://coralwebconcept.com/wp-content/uploads/2021/11/mobile-app-development.png",
      name: "advanced flutter course",
      instru: "james zaki",
      views: "3100",
      text: "  Learn mobile development with professional teachers",
      price: "250",
      priceValue: "151-300",
    },
    {
      id: 3,
      img: "https://1z1euk35x7oy36s8we4dr6lo-wpengine.netdna-ssl.com/wp-content/uploads/2020/08/zymr8_steps_the_mobile_app_dev_lifecycle_cover.jpg",
      name: " react native ",
      instru: "osama elzero",
      views: "2000",
      text: "  Learn mobile development with professional teachers",
      price: "120",
      priceValue: "91-150",
    },
    {
      id: 4,
      img: "https://static.tildacdn.com/tild6137-3465-4061-b861-306330633839/mobile-development-c.jpg",
      name: "backend infrastructure ",
      instru: "abdulrahman sami",
      views: "1200",
      text: "  Learn mobile development with professional teachers",
      price: "200",
      priceValue: "151-300",
    },
    {
      id: 5,
      img: "https://www.zintechnologies.com/demo2019/wp-content/uploads/2019/02/Mobile-Application-Development.jpg",
      name: "flutter course",
      instru: "mohamed ali",
      views: "1200",
      text: "  Learn mobile development with professional teachers",
      price: "90",
      priceValue: "40-90",
    },
    {
      id: 6,
      img: "https://www.jiasaz.com/public/images/mobile-app-development-for-startup-owners.jpeg",
      name: "HTMLl5",
      instru: "khalid jamal",
      views: "1200",
      text: "  Learn mobile development with professional teachers",
      price: "40",
      priceValue: "40-90",
    },
    {
      id: 7,
      img: "http://codecondo.com/wp-content/uploads/2016/05/9_Cross-platform_mobile_app_development_tools.jpg",
      name: "mobile development advanced course",
      instru: "Mustafa barzan",
      views: "1200",
      text: "  Learn mobile development with professional teachers",
      price: "190",
      priceValue: "91-150",
    },
    {
      id: 8,
      img: "https://gdcitsolutions.com/wp-content/uploads/Web-Design-Dev-Overview.jpg",
      name: " UI / UX Design",
      instru: "menna ali",
      views: "1200",
      text: "  Learn mobile development with professional teachers",
      price: "60",
      priceValue: "40-90",
    },
    {
      id: 9,
      img: "https://www.pix2apps.com/images/mobile/mobile-app.jpg",
      name: "Mobile App Front-Ende",
      instru: "Mustafa barzan",
      views: "1200",
      text: "  Learn mobile development with professional teachers",
      price: "90",
      priceValue: "40-90",
    },
  ],
};

export default data;
